#!/usr/bin/env python3

import sys
import argparse
import spg.layout

class PDF (spg.layout.Layout):

    def __init__ (self, infile, outfile):
        super().__init__ (infile)
        self.pd.write (outfile, prog = 'fdp', format = 'pdf')

if __name__ == "__main__":

    parser = argparse.ArgumentParser(description='SPG PDF output')
    parser.add_argument('--input',  action='store', nargs=1, required=True, help='Input file',  dest='input');
    parser.add_argument('--output', action='store', nargs=1, required=True, help='Output file', dest='output');
    parser.add_argument('--verbose', action='store_true', required=False, help='Verbose output', dest='verbose');
    args = parser.parse_args ()

    err.verbose (args.verbose)
    PDF (args.input[0], args.output[0])
