#!/usr/bin/env python3

import argparse
import sys

from spg.error import warn, info, err
from spg.graph import Graph

def main(args):

    # Read in graph
    G = Graph (args.input[0])
    G.write (args.output[0])

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='SPG Analyzer')
    parser.add_argument('--input', action='store', nargs=1, required=True, help='Input file', dest='input');
    parser.add_argument('--output', action='store', nargs=1, required=True, help='Output file', dest='output');
    parser.add_argument('--verbose', action='store_true', required=False, help='Verbose output', dest='verbose');

    try:
        args = parser.parse_args ()
        main(args)
    except Exception as e:
        err (e)
        raise
